<!DOCTYPE html>
<html>
<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Cache-control" content="no-cache">

<title>PowerHouse</title>

<link rel="stylesheet" href="common/css/bootstrap-5.1.3-dist/css/bootstrap.css">
<link rel="stylesheet" href="common/icofont/icofont.css">
<link rel="stylesheet" href="common/css/maincustom.css">

<link rel="icon" href="../../powerhouse/IMAGE_PLUG/logo-1.png" type="image/x-icon">

<style type="text/css">
  #app_bg_wall{
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: 100% auto;
    background-image: url('graphics/bg_image.jpg');
    background-position: unset;
    height: 100vh;
  }
</style>
<script type="text/javascript"></script>
<script src="common/js/jquery-3.6.0.js"></script>
<script src="common/css/bootstrap-5.1.3-dist/js/bootstrap.js"></script>

<script type="text/javascript" language="JavaScript">
window.addEventListener('contextmenu', function (e) { 
    // Custom Code IN Here
    e.preventDefault(); 
}, false);
</script>

</head>

<body id="app_bg_wall">

<style type="text/css">
  form{
    width: 100%;
    max-width: 600px;
    margin: 0 auto;
    padding: 40px;
    padding-top: 20px !important;
    border-radius: 5px;
    border: 1px solid #202020;
    margin-top:20px;
  }
  form div{
    width: 100%;
    display: inline-block !important;
    vertical-align: top !important;
    padding: 0px 10px;
  }
  .form-group{
    margin: 10px 0px !important;
  }
  @media(max-width: 768px){
    form div{
      width: 100% !important;
      display: inline-block !important;
    }
  }
</style>

<div class="container">
    <div class="row" style="margin: 0px !important;">

		<div class="col-12 text-center">
			<?php

			if (isset($_POST['reset_password'])) {

				require_once "db.php";

				$email = $_POST['email'];

				$auto_generated_password = rand(100000, 999999);

				function generatePassword($length = 10) {
                
		        	$charset = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
		        	$charsetLength = strlen($charset);
		        	$password = '';
		        
		        	for ($i = 0; $i < $length; $i++) {
		        		$randomIndex = rand(0, $charsetLength - 1);
		        		$password .= $charset[$randomIndex];
		        	}
		        
		        	return $password;
		        
		        }
		        
		        $autoGeneratedPassword = generatePassword();

				$sql = "UPDATE users SET password = '$autoGeneratedPassword' WHERE email = '$email'";
				mysqli_query($conn,$sql);

				$sender = "info.cobeo@gmail.com";
				$recipient = $email;
				$subject = 'Cobeo - Your New Password';
				$message = $autoGeneratedPassword;
				$headers = "From: ".$email."\r\n";

				if (mail($recipient, $subject, $message, $headers)){
				    echo "<script>window.alert('Password reset successfull. Please check your email inbox or spam folder.');</script>";
				}else{
				    echo "<script>window.alert('Error: Email not accepted. Please check the availability of the given email.');</script>";
				}

			}

			?>
			<form method="post" action="#" class="form-bg-all-glass" enctype="multipart/form-data">
				<div style="width: 100%;text-align: center;">
		          <a href="index.php">
		            <img src="assets/images/home.png" style="width:25px;height:auto;font-size:20px;float:left;"></i>
		          </a>
		          <span style="display:none;float:right;"><strong>DiaperBoutique SL</strong></span>
		        </div>
		        <br><br>
		        <div style="width: 100%;text-align: center;">
		          <h3 class="login-title">Reset Password</h3>
		        </div>
		        <br>
				<div class="form-group" style="text-align:left;">
		          	<label style="padding-bottom:7px;">Email:</label><br>
		          	<input type="email" class="form-control" name="email" placeholder="Email" autofocus="true" required/>
		        </div>
				<div class="form-group" style="width:100%;text-align:center;">
	          		<input type="submit" value="Send New Password" name="reset_password" class="btn btn-primary"/><br>
	          		<p class="link"><br><a href="login.php"><u> Login Now </u></a></p>
	        	</div>
	        </form>
		</div>

	</div>
</div>	

<script type="text/javascript"></script>
<script src="common/js/jquery-3.6.0.js"></script>
<script src="common/css/bootstrap-5.1.3-dist/js/bootstrap.js"></script>
<script src="common/js/maincustom.js"></script>
<script src="common/js/customtheme.js"></script>

</body>

</html>

























